openapi: 3.0.0
info:
  title: DICT API
  version: '1.0'
  description: |
    A API do DICT é o serviço que do arranjo PIX que permite buscar os detalhes de uma conta transacional através de seu identificar no diretório de chaves transacionais. Este identificador, chave, pode ser do tipo mais conveniente ao usuário, tendo disponíveis os seguintes tipos EMAIL, TELEFONE, CPF, CNPJ e EVP.
servers:
  - url: 'https://apigatewayuat.bvnet.bv'
tags:
  - name: Directory
    x-displayName: Diretório
    description: |- 
      O diretório de identificadores de contas transacionais é um conjunto de vínculos.
      Um vínculo é uma associação entre uma chave de endereçamento, uma conta transacional e seu dono.
      O dono pode ser uma pessoa física ou uma pessoa jurídica. A chave de endereçamento é usada identificar um vínculo.
      
      Os tipos de chave suportadas atualmente são as seguintes:
      
      |  Tipo         | Exp. regular                                                                                               | Exemplo                              | Comentário                                                                |
      |---------------|------------------------------------------------------------------------------------------------------------|--------------------------------------|---------------------------------------------------------------------------|
      | CPF           |  ^\[0-9\]{11}$                                                                                             | 12345678901                          |                                                                           |
      | CNPJ          |  ^\[0-9\]{14}$                                                                                             | 12345678901234                       |                                                                           |
      | PHONE         |  ^\\+\[1-9\]\[0-9\]\d{1,14}$                                                                               | +5510998765432                       |                                                                           |
      | EMAIL         |  [e-mails válidos W3C HTML5](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address)       | pix@bcb.gov.br                       | E-mail deve possuir no máximo 77 caracteres e deve ser em minúsculo       | 
      | EVP           |  [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}                                              | 123e4567-e89b-12d3-a456-426655440000 | Endereço Virtual de Pagamento é um tipo de chave é gerado pelo DICT       |
      Novos tipos de chave poderão vir a ser adicionados no futuro. Logo, é importante que a implementação de clientes
      seja flexível, permitindo a adição de novos tipos de chave.

paths:
  '/v1/dict/entries/{key}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entry'
      operationId: get-v1-dict-entries
      description: Endpoint para buscar dados de uma conta transacional através de seu identificador
      tags:
        - Directory
      parameters:
        - schema:
            type: string
          in: header
          name: document
          description: CNPJ do parceiro
          required: true
        - schema:
            type: string
          in: header
          name: endToEnd
          required: true
          description: Identificador fim-a-fim do pagamento associado a essa requisição. Corresponde ao campo EndToEndId na mensagem pacs.008. Usado para rate-limiting.
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
    delete:
      summary: ''
      operationId: delete-v1-dict-entries-key
      responses:
        '200':
          description: OK
components:
  schemas:
    Entry:
      title: Entry
      type: object
      properties:
        key:
          type: string
        keyType:
          type: string
        owner:
          $ref: '#/components/schemas/Owner'
        account:
          $ref: '#/components/schemas/Account'
        creationDate:
          type: string
        keyOwnershipDate:
          type: string
      required:
        - key
        - keyType
        - owner
        - account
    Owner:
      title: Owner
      type: object
      properties:
        type:
          type: string
        taxIdNumber:
          type: string
        name:
          type: string
        tradeName:
          type: string
      required:
        - type
        - taxIdNumber
        - name
    Account:
      title: Account
      type: object
      properties:
        participant:
          type: string
        accountNumber:
          type: string
        accountType:
          type: string
        branch:
          type: string
      required:
        - participant
        - accountNumber
